title: Geek
description: "Some Notes about Work"
author:
  name: "Ikki"
  email: "ikkiday@163.com"
  url: "https://ikki-dai.github.io/blogs/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Ikki"
year : "2019"
